
function uwb_re_config(this_block)

  % Revision History:
  %
  %   29-May-2013  (10:07 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\03.Subject\20122\UWB 802.15.4a\Report\AnhNTK53-DATN-2013\AnhNTK53\Project\uwb_re_simulink_hil\uwb_re.v
  %
  %

  this_block.setTopLevelLanguage('Verilog');

  this_block.setEntityName('uwb_re');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('in_start');
  this_block.addSimulinkInport('in_rst');
  this_block.addSimulinkInport('in_data');
  this_block.addSimulinkInport('ddph_i');
  this_block.addSimulinkInport('sfd_threshold');
  this_block.addSimulinkInport('sm_threshold');

  this_block.addSimulinkOutport('data_out');
  this_block.addSimulinkOutport('psdu_en');
  this_block.addSimulinkOutport('coarse_off');
  this_block.addSimulinkOutport('coarse_error');

  data_out_port = this_block.port('data_out');
  data_out_port.setType('UFix_1_0');
  data_out_port.useHDLVector(false);
  psdu_en_port = this_block.port('psdu_en');
  psdu_en_port.setType('UFix_1_0');
  psdu_en_port.useHDLVector(false);
  coarse_off_port = this_block.port('coarse_off');
  coarse_off_port.setType('UFix_1_0');
  coarse_off_port.useHDLVector(false);
  coarse_error_port = this_block.port('coarse_error');
  coarse_error_port.setType('UFix_1_0');
  coarse_error_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('in_start').width ~= 1);
      this_block.setError('Input data type for port "in_start" must have width=1.');
    end

    this_block.port('in_start').useHDLVector(false);

    if (this_block.port('in_rst').width ~= 1);
      this_block.setError('Input data type for port "in_rst" must have width=1.');
    end

    this_block.port('in_rst').useHDLVector(false);

    if (this_block.port('in_data').width ~= 8);
      this_block.setError('Input data type for port "in_data" must have width=8.');
    end

    if (this_block.port('ddph_i').width ~= 3);
      this_block.setError('Input data type for port "ddph_i" must have width=3.');
    end

    if (this_block.port('sfd_threshold').width ~= 32);
      this_block.setError('Input data type for port "sfd_threshold" must have width=32.');
    end

    if (this_block.port('sm_threshold').width ~= 16);
      this_block.setError('Input data type for port "sm_threshold" must have width=16.');
    end

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('uwb_re.v');
  this_block.addFile('uwb_re_submodules.v');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

